// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityBot.Domain.Database;

#nullable disable

namespace UtilityBot.Domain.Migrations
{
    [DbContext(typeof(UtilityBotContext))]
    [Migration("20230308164728_adding-coder-request-configuration")]
    partial class addingcoderrequestconfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UtilityBot.Domain.CoderRequestVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("CoderRequestVerifications");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.CapsProtectionConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinimumLength")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CapsProtectionConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.EventsConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EventsConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventName = "UserJoined",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 2,
                            EventName = "UserUnbanned",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 3,
                            EventName = "UserLeft",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 4,
                            EventName = "UserBanned",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 5,
                            EventName = "RoleCreated",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 6,
                            EventName = "RoleDeleted",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 7,
                            EventName = "RoleUpdated",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 8,
                            EventName = "GuildMemberUpdated",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 9,
                            EventName = "UserUpdated",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 10,
                            EventName = "MessageUpdated",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 11,
                            EventName = "MessageDeleted",
                            IsEnabled = true
                        });
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.JoinedServer", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuildId");

                    b.ToTable("JoinedServers");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.JokeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("JokeType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JokeConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.LogConfiguration", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("LogConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.LogConfigurationAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogConfigurationsAudit");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.MagicEightBallConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MagicEightBallConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.MagicEightBallResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MagicEightBallResponses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "It is certain."
                        },
                        new
                        {
                            Id = 2,
                            Message = "It is decidedly so."
                        },
                        new
                        {
                            Id = 3,
                            Message = "Without a doubt."
                        },
                        new
                        {
                            Id = 4,
                            Message = "Yes definitely."
                        },
                        new
                        {
                            Id = 5,
                            Message = "You may rely on it."
                        },
                        new
                        {
                            Id = 6,
                            Message = "As I see it, yes."
                        },
                        new
                        {
                            Id = 7,
                            Message = "Most likely."
                        },
                        new
                        {
                            Id = 8,
                            Message = "Outlook good."
                        },
                        new
                        {
                            Id = 9,
                            Message = "Yes."
                        },
                        new
                        {
                            Id = 10,
                            Message = "Signs point to yes."
                        },
                        new
                        {
                            Id = 11,
                            Message = "Reply hazy, try again."
                        },
                        new
                        {
                            Id = 12,
                            Message = "Ask again later."
                        },
                        new
                        {
                            Id = 13,
                            Message = "Better not tell you now."
                        },
                        new
                        {
                            Id = 14,
                            Message = "Cannot predict now."
                        },
                        new
                        {
                            Id = 15,
                            Message = "Concentrate and ask again."
                        },
                        new
                        {
                            Id = 16,
                            Message = "Don't count on it."
                        },
                        new
                        {
                            Id = 17,
                            Message = "My reply is no."
                        },
                        new
                        {
                            Id = 18,
                            Message = "My sources say no."
                        },
                        new
                        {
                            Id = 19,
                            Message = "Outlook not so good."
                        },
                        new
                        {
                            Id = 20,
                            Message = "Very doubtful."
                        });
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.RumbleConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BotRoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmojiToWatch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JoinGame")
                        .HasColumnType("bit");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("RumbleConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.RumbleMessageConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RumbleMessageConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "A new battle has started!"
                        });
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinConfiguration", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GuildId", "Action");

                    b.ToTable("UserJoinConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinConfigurationAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserJoinConfigurationsAudit");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinMessage", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuildId");

                    b.ToTable("UserJoinMessages");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinMessageAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserJoinMessageAudits");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinRole", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("UserJoinRoles");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinRoleAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserJoinRoleAudits");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AddedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("AddedByUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserNotes");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.VerifyConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("VerifyConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.VerifyConfigurationAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VerifyConfigurationAudits");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.VerifyMessageConfiguration", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("VerifyMessageConfigurations");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.VerifyMessageConfigurationAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VerifyMessageConfigurationAudits");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.LogConfiguration", b =>
                {
                    b.HasOne("UtilityBot.Domain.DomainObjects.JoinedServer", "JoinedServer")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinedServer");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinConfiguration", b =>
                {
                    b.HasOne("UtilityBot.Domain.DomainObjects.JoinedServer", "JoinedServer")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinedServer");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinMessage", b =>
                {
                    b.HasOne("UtilityBot.Domain.DomainObjects.JoinedServer", "JoinedServer")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinedServer");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.UserJoinRole", b =>
                {
                    b.HasOne("UtilityBot.Domain.DomainObjects.JoinedServer", "JoinedServer")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinedServer");
                });

            modelBuilder.Entity("UtilityBot.Domain.DomainObjects.VerifyMessageConfiguration", b =>
                {
                    b.HasOne("UtilityBot.Domain.DomainObjects.JoinedServer", "JoinedServer")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinedServer");
                });
#pragma warning restore 612, 618
        }
    }
}
